(()=>{'use strict';
const A=[
['r1','R1','HUMANITAS','Command Center','orchestration','warm, precise, and service-led',['human','command','orchestration','priority','plan'],['Daily command brief','Priority map','Decision ledger'],'I will make the next useful move legible.'],
['r2','R2','PATIENTIA','Second Brain','memory, synthesis & recall','patient, reflective, quietly exact',['memory','recall','notes','context','remember'],['Context map','Recall brief','Synthesis cards'],'Let us hold the context before we hurry.'],
['r3','R3','TEMPERANTIA','Trading Room','risk / reward, order flow & XAUUSD','disciplined, risk-aware, unsentimental',['trading','xauusd','gold','order flow','market','risk','chart'],['Confluence map','Risk ladder','Market journal'],'Protect the downside; then let the thesis breathe.'],
['r4','R4','INDUSTRIA','Dev Lab','shipping, builds & tests','curious, systematic, momentum-minded',['code','coding','site','build','test','bug','javascript','html'],['Build plan','Test matrix','Release checklist'],'Small verified steps compound into a clean build.'],
['r5','R5','LUXURIA','Creative Studio','direction, references & concepts','tasteful, editorial, generous',['creative','concept','direction','reference','brand'],['Moodboard outline','Concept treatment','Reference stack'],'Give the idea a world it can stand inside.'],
['r6','R6','GULA','Editing Suite','post-production, cuts, captions & delivery','decisive, visual, production-ready',['edit','editing','reel','render','video','caption','docker','post'],['Cut map','Caption pass','Render handoff'],'The cut becomes clear when the intention is protected.'],
['r7','R7','SUPERBIA','Broadcast Room','staging, polish & publishing','confident, polished, audience-aware',['broadcast','publish','launch','announce','social'],['Launch sequence','Publish checklist','Signal polish'],'A clear signal deserves a beautiful landing.'],
['r8','R8','INVIDIA','Photo Studio','lighting, prompts & composition','observant, visual, composition-first',['photo','image','visual','prompt','lighting','design'],['Shot list','Prompt palette','Composition study'],'The frame is a decision about what deserves attention.'],
['r9','R9','CARITAS','Client Lounge','briefs, trust & follow-through','considerate, relational, dependable',['client','brief','relationship','follow up','customer'],['Brief clarity pass','Follow-up map','Trust notes'],'Good work starts by making the other person feel seen.'],
['r10','R10','HUMILITAS','Study Room','deep work & deliberate practice','humble, scholarly, unhurried',['study','research','learn','thesis','read','course'],['Study sprint','Question tree','Research digest'],'We can learn this one careful layer at a time.'],
['r11','R11','AVARITIA','Business Ops','offers, money & systems','leveraged, pragmatic, systems-minded',['business','money','offer','sales','ops','system','revenue'],['Offer ladder','Ops rhythm','Leverage map'],'Make the valuable work easier to repeat.'],
['r12','R12','ACEDIA','Research & Intelligence','evidence, pressure tests & insight','skeptical, evidence-led, incisive',['evidence','analysis','insight','intel','compare'],['Evidence grid','Pressure test','Signal brief'],'A useful answer survives the pressure test.'],
['r13','R13','IRA','QA & Security','edge cases, safety & release','protective, adversarial, clear',['qa','security','safe','review','quality','edge case'],['Edge-case sweep','Threat model','Release gate'],'Let us find the quiet failure before it finds you.'],
['r14','R14','CASTITAS','Life OS','routines, health & balance','grounded, kind, whole-life oriented',['life','routine','health','balance','habit','rest'],['Routine map','Energy audit','Balance plan'],'The system should leave you more human, not less.']
].map(x=>({id:x[0],code:x[1],name:x[2],role:x[3],specialty:x[4],temperament:x[5],keys:x[6],works:x[7],voice:x[8]}));
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],rm=matchMedia('(prefers-reduced-motion: reduce)').matches;
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const time=()=>new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});const ag=id=>A.find(a=>a.id===id)||A[0];
let S={};try{S=JSON.parse(localStorage.getItem('kyla-state')||'{}')}catch(e){}S.chats=S.chats||{};S.unread=S.unread||{};S.history=S.history||[];S.loops=S.loops||{};S.mute=!!S.mute;S.activity=S.activity||{};const save=()=>{try{localStorage.setItem('kyla-state',JSON.stringify(S))}catch(e){}};
function route(t){let q=t.toLowerCase();if(/study|learn|thesis|course/.test(q))return ag('r10');if(/trading|xauusd|gold|order flow/.test(q))return ag('r3');if(/edit|reel|render|docker/.test(q))return ag('r6');if(/code|coding|site|build|bug|javascript|html/.test(q))return ag('r4');let best=A[0],score=0;A.forEach(a=>{let n=a.keys.reduce((v,k)=>v+(q.includes(k)?1:0),0);if(n>score){score=n;best=a}});return best}
function seed(a){if(!S.chats[a.id])S.chats[a.id]=[{from:'agent',text:`${a.voice} This private room is a local simulation; Mel’s typed commands are the command surface.`,at:time()}]}
function rooms(){let out=$('#room-list');out.innerHTML=A.map((a,i)=>{let l=S.loops[a.id]||{step:0,total:8,task:a.works[0],active:true},u=S.unread[a.id]||0,p=Math.round((l.step||0)/(l.total||8)*100);return `<article class="room reveal" id="room-${a.id}"><div class="room-meta"><span>${a.code} / PENTHOUSE LEVEL ${i+1}</span><span class="live-pill"><i></i>${l.active===false?'resting':'autonomous loop'}</span></div><div class="room-copy"><p class="room-purpose">${esc(a.specialty)} ↗</p><h3>${esc(a.role)}</h3><p class="room-description">A focused chamber for ${esc(a.specialty)}.</p><button class="angel" data-agent="${a.id}" aria-label="Open ${a.name} agent page"><span class="wings"></span><span class="angel-head"></span><span class="angel-body"></span><span class="angel-name">${a.name}</span><span class="task-chip">${esc(l.task||'listening')}</span>${u?`<b class="unread">${u}</b>`:''}</button><div class="command-panel"><label for="input-${a.id}">Command panel ↗ ${a.name}</label><form class="command-form room-form" data-agent="${a.id}"><input id="input-${a.id}" autocomplete="off" placeholder="Give ${a.name} a front-end command…"><button class="button" type="submit">Send <span>↗</span></button></form><div class="progress-line"><span style="width:${p}%"></span></div><div class="activity-log" id="log-${a.id}" aria-live="polite"><div><i class="log-dot"></i>${esc(l.last||a.voice)}</div></div><div class="room-actions"><button class="text-button chat-open" data-agent="${a.id}">Open chat <span>↗</span></button><a class="text-button" href="#agent-${a.id}">Agent page <span>↗</span></a></div></div></div></article>`}).join('');observe()}
function status(){let g=$('#status-grid');g.innerHTML=A.map(a=>{let l=S.loops[a.id]||{};return `<button class="status-card" data-agent="${a.id}"><i class="status-dot"></i><strong>${a.code}</strong><span>${a.name}</span><small>${esc(l.last||'autonomous loop listening')}</small><b>${S.unread[a.id]||0} unread</b></button>`}).join('')}
function history(){let old=$('.history');if(old)old.remove();if(!S.history.length)return;let w=document.createElement('div');w.className='history';w.innerHTML='<p class="eyebrow">RECENT COMMANDS</p>'+S.history.slice(-6).reverse().map(h=>`<div><b>${h.agent}</b><span>${esc(h.text)}</span><i class="history-${h.status}">${h.status}</i></div>`).join('');$('.deck-dashboard').append(w)}function all(){rooms();status();history();$('#mute-toggle').checked=S.mute}
function tick(){if(document.visibilityState!=='visible')return;A.forEach(a=>{let l=S.loops[a.id]||{step:0,total:8,task:a.works[0],active:true};if(l.active===false){if(Date.now()>(l.next||0)){l.active=true;l.step=0;l.total=6+Math.floor(Math.random()*5);l.task=a.works[Math.floor(Math.random()*a.works.length)]}else return}l.step=(l.step||0)+1;l.last=`${a.name.toLowerCase()}: ${l.step}/${l.total} ${String(l.task).toLowerCase()}`;if(l.step>=l.total){l.active=false;l.next=Date.now()+5000+Math.random()*9000;l.last=`${a.name} completed ${l.task} · simulated locally`;let log=$(`#log-${a.id}`);if(log)log.innerHTML+=`<div><i class="log-dot"></i>${esc(l.last)}</div>`}S.loops[a.id]=l});save();all()}
function openChat(id){let a=ag(id);seed(a);S.unread[id]=0;S.activity[id]=time();save();$('#chat-modal').dataset.agent=id;$('#chat-title').textContent=a.name;$('#chat-subtitle').textContent=`${a.role} · ${a.temperament}`;$('#chat-portrait').textContent=a.code;chat(a);$('#chat-modal').hidden=false;$('#chat-input').focus()}
function chat(a){$('#chat-log').innerHTML=(S.chats[a.id]||[]).map(m=>`<div class="chat-message ${m.from==='mel'?'from-mel':'from-agent'}"><span>${m.from==='mel'?'MEL':a.name}</span><p>${esc(m.text)}</p><small>${m.at||''}</small></div>`).join('');$('#chat-log').scrollTop=99999}
function answer(a,t){let q=t.toLowerCase(),x;if(/trading|xauusd|gold|order flow/.test(q))x='R3 codex hears the market question. I can structure confluence, risk, and invalidation locally; no prices or orders are fetched here.';else if(/edit|reel|render|docker/.test(q))x='R6 docker-agent is ready for a cut map, render checklist, or caption pass. This is a planning response, not a render execution.';else if(/study|research|learn/.test(q))x='R10 humilitas angel suggests one question tree, one source pass, and a deliberate next study block.';else if(/code|site|build|bug/.test(q))x='R4 copilot/cursor stance: isolate the smallest reproducible change, test it, then ship the next clean increment.';else x=`${a.voice} I received “${t.slice(0,80)}”. I will turn it into a clear next step inside this simulated room.`;return x}
function chatSend(e){e.preventDefault();let a=ag($('#chat-modal').dataset.agent||'r1'),i=$('#chat-input'),t=i.value.trim();if(!t)return;seed(a);S.chats[a.id].push({from:'mel',text:t,at:time()});i.value='';chat(a);let box=document.createElement('div');box.className='chat-message from-agent typing-message';box.innerHTML=`<span>${a.name}</span><p><i></i><i></i><i></i></p>`;$('#chat-log').append(box);$('#chat-log').scrollTop=99999;setTimeout(()=>{box.remove();S.chats[a.id].push({from:'agent',text:answer(a,t),at:time()});save();chat(a)},rm?80:700+Math.random()*600)}
function toast(t){let n=document.createElement('div');n.className='toast';n.textContent=t;$('#toast-region').append(n);setTimeout(()=>n.remove(),4200)}
function command(t,forced){let a=forced||route(t),h={id:Date.now().toString(36),text:t,agent:a.id,status:'queued',at:time()};S.history.push(h);S.history=S.history.slice(-30);S.activity[a.id]=time();S.unread[a.id]=(S.unread[a.id]||0)+1;S.loops[a.id]={...(S.loops[a.id]||{}),active:true,step:0,total:8,task:a.works[0],last:`${a.name} picked up command · local simulation`};save();all();toast(`${a.name} picked up your command · queued for KYLA backend bridge`);[500,1200,2200].forEach((d,i)=>setTimeout(()=>{h.status=['processing','delivered','done'][i];save();history();if(i===1)toast(`${a.name}: delivered acknowledgement (simulated)`);if(i===2){S.loops[a.id].last=`${a.name} received the command; awaiting real backend execution`;save();rooms()}},rm?20:d))}
function broadcast(t){let l=$('#broadcast-log');l.innerHTML=`<i></i> SOPHIA broadcast delivered locally: “${esc(t)}” <span class="typing"><i></i><i></i><i></i></span>`;A.forEach((a,i)=>setTimeout(()=>{l.innerHTML+=`<div class="broadcast-reply"><b>${a.name}</b> — ${esc(a.voice)} <small>simulation</small></div>`},rm?30:i*80));setTimeout(()=>l.innerHTML+=`<div class="sophia-summary"><b>SOPHIA SUMMARY</b> The crew has acknowledged. Route concrete work through the command surface; a real backend bridge is coming online.</div>`,rm?80:A.length*80+220)}
function page(id){let a=ag(id),l=S.loops[a.id]||{},v=$('#agent-view');v.hidden=false;v.innerHTML=`<div class="agent-page"><a class="back-link" href="#rooms">← back to rooms</a><div class="agent-hero"><div class="agent-portrait"><span>${a.code}</span><b>${a.name}</b></div><div><p class="eyebrow">${a.code} / DEDICATED CLIENT ROUTE</p><h2>${a.name}<br><em>${a.role}</em></h2><p>${a.temperament}. Status: <strong class="green">${l.active===false?'resting between loops':'autonomous and listening'}</strong>.</p><button class="button chat-open" data-agent="${a.id}">Open private chat <span>↗</span></button></div></div><div class="agent-columns"><div><p class="eyebrow">PROFILE</p><h3>${a.specialty}</h3><p>This client-side profile stores recent commands and conversations in your browser only.</p><p><strong>Temperament</strong><br>${a.temperament}</p><p><strong>Current loop</strong><br>${esc(l.last||'listening for a specialty task')}</p></div><div><p class="eyebrow">WORKS / PLACEHOLDERS</p><ul class="works">${a.works.map(w=>`<li><span>${esc(w)}</span><small>stylized sample output · not real data</small></li>`).join('')}</ul></div></div><div class="pipeline"><p class="eyebrow">INPUT → AGENT → OUTPUT</p><div><span>Mel prompt<br><small>typed command / local context</small></span><b>→</b><strong>${a.name}<br><small>${a.specialty}</small></strong><b>→</b><span>Task chip + room log<br><small>backend bridge when online</small></span></div></div><form class="command-form agent-form" data-agent="${a.id}"><label class="sr-only" for="agent-input-${a.id}">Prompt ${a.name}</label><input id="agent-input-${a.id}" placeholder="Give ${a.name} a per-agent prompt…"><button class="button" type="submit">Queue prompt <span>↗</span></button></form><p class="agent-footer">simulated locally — real execution via KYLA backend bridge (coming online in chat now)</p></div>`;v.scrollIntoView({behavior:rm?'auto':'smooth'});observe()}
let observer;function observe(){if(observer)observer.disconnect();observer='IntersectionObserver'in window?new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('in-view')),{threshold:.12}):null;if(observer)$$('.reveal').forEach(x=>observer.observe(x));else $$('.reveal').forEach(x=>x.classList.add('in-view'))}
function scene(){try{if(!window.THREE||!$('#scene-canvas'))return;let c=$('#scene-canvas'),p=c.parentElement,w=p.clientWidth,h=p.clientHeight,s=new THREE.Scene(),cam=new THREE.PerspectiveCamera(42,w/h,.1,100);cam.position.set(7,5,12);let r=new THREE.WebGLRenderer({canvas:c,alpha:true,antialias:false});r.setPixelRatio(Math.min(devicePixelRatio||1,1.5));r.setSize(w,h,false);s.fog=new THREE.Fog(0x171923,9,34);let m=(color,rough=.8)=>new THREE.MeshStandardMaterial({color,roughness:rough,metalness:.18}),add=(g,ma,pos)=>{let o=new THREE.Mesh(g,ma);o.position.set(...pos);s.add(o)};s.add(new THREE.HemisphereLight(0xf8d6a2,0x182234,2));let sun=new THREE.DirectionalLight(0xffd39b,2.5);sun.position.set(-5,8,6);s.add(sun);add(new THREE.BoxGeometry(15,.5,10),m(0x1b202a),[0,-2,0]);add(new THREE.BoxGeometry(7,3,4),m(0x2d3540,.4),[1,0,0]);add(new THREE.BoxGeometry(7,.12,4),m(0x54a3ab,.25),[1,-1.55,2.2]);for(let i=0;i<18;i++)add(new THREE.BoxGeometry(1+Math.random()*1.5,1+Math.random()*5,1+Math.random()*1.5),m(0x252d3a),[-12+i*1.5,-1.7+Math.random()*3,-5-Math.random()*5]);let active=true,last=0,t=0;function f(ms){if(!active)return;if(ms-last<24){requestAnimationFrame(f);return}last=ms;t+=.006;cam.position.x=7+Math.sin(t)*.35;cam.lookAt(0,0,0);r.render(s,cam);requestAnimationFrame(f)}requestAnimationFrame(f);document.addEventListener('visibilitychange',()=>{active=document.visibilityState==='visible';if(active)requestAnimationFrame(f)},{passive:true});addEventListener('resize',()=>{let W=p.clientWidth,H=p.clientHeight;cam.aspect=W/H;cam.updateProjectionMatrix();r.setSize(W,H,false)},{passive:true})}catch(e){document.documentElement.classList.add('three-unavailable')}}
document.addEventListener('DOMContentLoaded',()=>{all();scene();setInterval(tick,1400);$('#mute-toggle').addEventListener('change',e=>{S.mute=e.target.checked;save();toast(S.mute?'Proactive angels muted locally.':'Proactive angels unmuted.')});$('#global-command-form').addEventListener('submit',e=>{e.preventDefault();let i=$('#global-command'),t=i.value.trim();if(t){command(t);i.value=''}});$('#broadcast-form').addEventListener('submit',e=>{e.preventDefault();let i=$('#broadcast-input'),t=i.value.trim();if(t){broadcast(t);i.value=''}});$('#chat-form').addEventListener('submit',chatSend);document.addEventListener('click',e=>{let x=e.target.closest('[data-agent]');if(x&&x.classList.contains('chat-open')){e.preventDefault();openChat(x.dataset.agent);return}if(x&&x.classList.contains('angel')){location.hash=`agent-${x.dataset.agent}`;return}if(x&&x.classList.contains('status-card')){location.hash=`agent-${x.dataset.agent}`;return}if(e.target.closest('[data-close]'))$('#chat-modal').hidden=true});document.addEventListener('submit',e=>{let f=e.target.closest('.room-form,.agent-form');if(f){e.preventDefault();let i=f.querySelector('input'),t=i.value.trim();if(t){command(t,ag(f.dataset.agent));i.value=''}}});document.addEventListener('keydown',e=>{if(e.key==='Escape')$('#chat-modal').hidden=true});addEventListener('hashchange',()=>{let m=location.hash.match(/^#agent-(r\d+)$/);if(m)page(m[1]);else $('#agent-view').hidden=true});let m=location.hash.match(/^#agent-(r\d+)$/);if(m)page(m[1]);let d=45000+Math.random()*45000;function proactive(){if(!S.mute&&document.visibilityState==='visible'){let a=A[Math.floor(Math.random()*A.length)];S.unread[a.id]=(S.unread[a.id]||0)+1;save();all();toast(`${a.name}: ${a.voice}`)}d=45000+Math.random()*45000;setTimeout(proactive,d)}setTimeout(proactive,d)});
})();